services:
  dev-db:
    image: postgres:16
    ports:
      - 5434:5432
    container_name: expense-tracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: expensestracker
      